---
- name: copy redis.conf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
    backup: yes
    owner: root
    group: root
  with_items:
    - { src: roles/redis/files/redis.conf, dest: . }
  tags:
    - redis.conf
