---
- name: copy httpd conf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/httpd/{{ item.dest }}"
    backup: yes
    owner: root
    group: root
  with_items:
    - { src: roles/apache/files/httpd.conf, dest: . }
    - { src: roles/apache/files/sites-enabled/adachin.conf, dest: conf.d/adachin.conf }
    - { src: roles/apache/files/sites-enabled/stage.conf, dest: conf.d/stage.conf }
  tags:
    - httpd-conf
