- name: install yum packages
  yum: name={{ item }} state=latest
  with_items:
  - httpd24
  - python-setuptools

- name: install easy_install package
  easy_install: name=pip

- name: install pip package
  pip: name=httplib2

- name: copy index.html
  copy: src=roles/apache/files/index.html dest=/var/www/html

- name: start httpd
  sudo: True
  service: name=httpd enabled=yes state=started

- name: check httpd is working
  uri: url=http://localhost/

- name: apache sites-enabled
  file: path=/etc/httpd/sites-enabled state=directory owner=root group=root mode=0755

- file: path=/var/www/{{ item.name }} state=directory owner=root group=root mode=0755
  with_items:
        - { name: 'adachin' }
        - { name: 'stage' }
