if [ -f ~/.bashrc ] ; then
  . ~/.bashrc
  fi


  export PATH=/opt/local/bin:/opt/local/sbin:$PATH
  export PATH=/opt/local/bin:/opt/local/sbin:$PATH
  export GEM_HOME=~/.gem/ruby/1.8
  export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
  export CLICOLOR=1
  export LSCOLORS=ExFxBxDxCxegedabagacad
  export PS1='\h:\W \d \t \$ '
  export PS1="\[\e[1;32m\][@\h:\w]\$\[\e[00m\] "



# exec $SHELL -l シェル再起動
