---
#- action: ec2_facts
#- name: Server Name
#  action: debug msg={{ ec2_tag_Name }}

- name: /etc/sysconfig/i18n
  lineinfile:
    dest: /etc/sysconfig/i18n
    line: 'LANG={{ locale }}'
    regexp: 'LANG=en_US.UTF-8'

- name: /etc/sysconfig/clock
  lineinfile:
    dest: /etc/sysconfig/clock
    line: 'ZONE={{ timezone }}'
    regexp: 'ZONE=UTC'

- name: /etc/sysconfig/clock
  lineinfile:
    dest: /etc/sysconfig/clock
    line: 'UTC=false'
    regexp: 'UTC=true'


- name: set /etc/localtime to {{ timezone }}
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes mode=0644

- name: install common packages
  yum: name={{ item }} state=latest
  with_items:
    - tmux
    - tree
    - zsh
    - zabbix

 #ruby
- shell: echo 'export PATH="/root/.rbenv/bin:$PATH"' >> /root/.bashrc
  sudo: no
- shell: echo 'export PATH="/root/.rbenv/shims:$PATH"' >> /root/.bashrc
  sudo: no
- shell: echo 'eval "$(rbenv init -)"' >> /root/.bashrc
  sudo: no
- shell: source /root/.bashrc
  sudo: no

- git: >
  repo=https://github.com/sstephenson/rbenv.git
  dest=/root/.rbenv/
- git: >
  repo=https://github.com/sstephenson/ruby-build.git
  dest=/root/.rbenv/plugins/ruby-build/
- file: path=/root/.rbenv owner=root state=directory recurse=yes

- shell: /root/.rbenv/bin/rbenv install -v 2.2.2
  sudo: no
- shell: /root/.rbenv/bin/rbenv rehash
  sudo: no
- shell: /root/.rbenv/bin/rbenv global 2.2.2
  sudo: no


- name: limits.conf
  copy:
    src: limits.conf
    backup: yes
    dest: /etc/security/limits.conf


- name: /etc/rc.d/rc.local create swap
  blockinfile:
    dest: /etc/rc.d/rc.local
    create: yes
    block: |
      dd if=/dev/zero of=/media/ephemeral0/swapfile bs=1M count=1024;
      chmod 600 /media/ephemeral0/swapfile;
      mkswap /media/ephemeral0/swapfile;
      swapon /media/ephemeral0/swapfile;


