---
- name: create user
  user:
    name: adachin
    password: "{{ 'adachindayo' | password_hash('sha512') }}"
    shell: /bin/bash
    group: wheel

- name: authorized_key for user
  authorized_key:
    user: adachin
    key: "ssh-~~~~~~"
