---
- name: haproxy.cfg
  template:
    src: roles/haproxy/templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes

#- name: check config file
  #shell: /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -c
  #register: out

#- debug: var=out

#- name: haproxy logrotate
#  template:
#    src: roles/haproxy/files/logrotate/haproxy
#    dest: /etc/logrotate.d/
#    backup: no
#  notify: restart rsyslogd
