# Getting Base Image
FROM centos:6

# start install nginx
RUN yum update -y
RUN yum install -y vim
RUN yum install -y curl
RUN rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
RUN yum install -y nginx
RUN /etc/init.d/nginx start
RUN chkconfig nginx on

# start install mysql
RUN yum -y install mysql-server
RUN /etc/init.d/mysqld start
RUN chkconfig mysqld on

# start install php
RUN yum -y install php
RUN yum -y install php-mysql


# Port
EXPOSE 22 80

# echo running
CMD ["echo", "running!"]
