---
- name: copy my.cnf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
    backup: yes
    owner: root
    group: root
  with_items:
    - { src: roles/mysql/files/my.cnf, dest: . }
  tags:
    - my.cnf
