---
- name: install php
  sudo: True
  yum: name={{item}}
  with_items:
    - php56
    - json-c
    - php56-cli
    - php56-common
    - php56-jsonc
    - php56-process
    - php56-xml
    - php56-mysqlnd

- name: copy phpinfo.php
  copy: src=roles/php/files/phpinfo.php dest=/var/www/gmo-ccg

#- name: change php time-zone
#  sudo: True
#  replace: dest=/etc/php.ini regexp="^;date\.timezone =" replace="date.timezone = Asia/Tokyo" backup=yes
