---
- name: Add Remi repository 'php-repo'
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: install php
  yum: pkg={{item}} state=present enablerepo=remi,remi-php56
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-gd
    - php-cli
    - php-dbg
    - php-pecl-xdebug
    - php-pear
    - php-pecl-mailparse

- name: Add repository 'php-mecab'
  yum: name=http://packages.groonga.org/centos/groonga-release-1.1.0-1.noarch.rpm state=present

- name: install php-mecab
 # yum: name={{item}}
  yum: name={{item}} state=latest enablerepo=groonga
  with_items:
    - mecab
    - mecab-ipadic
    - mecab-devel
    - php-mecab

- name: install php-more
  yum: name={{item}} state=latest
  with_items:
    - php-common
    - php-devel
    - php-mysql
    - php-redis

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin

- name: move composer.phar to composer
  command: mv /usr/bin/composer.phar /bin/composer

- name: copy phpinfo.php
  copy: src=roles/php/files/phpinfo.php dest=/var/www

- name: change php time-zone
  sudo: True
  replace: dest=/etc/php.ini regexp="^;date\.timezone =" replace="date.timezone = Asia/Tokyo" backup=yes
