#-name: php yum repository
# copy:
#  src: yum.repos.d/php.repo
#  dest: /etc/yum.repos.d
#  mode: 0644
#  owner: root
#  group: root

#- name: Install php
#  sudo: True
#  yum: name={{ item }} state=present enablerepo=php
#  with_items:
#- php-cli
#- php-pear
#- php-mysql
#- php-mbstring
#- php-gd
#- php-mcrypt
#- php-pecl-apc

- name: install php
  yum: pkg={{ item }} state=installed enablerepo=remi,remi-php56
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-gd
    - php-cli
    - php-dbg
    - php-pecl-xdebug
    - php-pear
    - php-pecl-mailparse

#- name: test phpfile
#  shell: "echo '<?php phpinfo() ?>' > /var/www/html/info.php"
#  args:
#  creates: "/var/www/gmo-ccg/info.php"
