---
- name: install php
  sudo: True
  yum: name={{item}}
  with_items:
    - php56
    - json-c
    - php56-cli
    - php56-common
    - php56-jsonc
    - php56-process
    - php56-xml
    - php56-mysqlnd

#- name: test phpfile
#  shell: "echo '<?php phpinfo() ?>' > /var/www/html/info.php"
#  args:
#  creates: "/var/www/gmo-ccg/info.php"
