---
- name: Add Remi repository 'php-repo'
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: install php
  yum: pkg={{item}} state=present enablerepo=remi,remi-php56
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-gd
    - php-cli
    - php-dbg
    - php-pecl-xdebug
    - php-pear
    - php-pecl-mailparse


- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin

- name: move composer.phar to composer
  command: mv /usr/bin/composer.phar /bin/composer

- name: Add repository 'mecab'
  yum: name=http://packages.groonga.org/centos/groonga-release-1.1.0-1.noarch.rpm state=present

- name: install packages
  yum: name={{ item }} state=installed
  with_items:
    - mecab
    - mecab-ipadic
    - mecab-devel


- name: copy phpinfo.php
  copy: src=roles/php/files/phpinfo.php dest=/var/www

- name: change php time-zone
  sudo: True
  replace: dest=/etc/php.ini regexp="^;date\.timezone =" replace="date.timezone = Asia/Tokyo" backup=yes

- name: download php-mecab
get_url:  
  url: https://github.com/rsky/php-mecab/archive/master.zip
  dest: /tmp

- name: untar php-mecab source archive
  unarchive:
  src: /tmp/master.zip
  dest: /tmp
  copy: no

- name: phpize
  shell: phpize
  args:
  chdir: /tmp/php-mecab-master/mecab

- name: configure php-mecab
  shell: >-
    ./configure
  args:
  chdir: /tmp/php-mecab-master/mecab

- name: configure php-mecab config
  shell: >-
    ./configure --with-php-config=/usr/bin/php-config --with-mecab=/usr/local/bin/mecab-config
  args:
  chdir: /tmp/php-mecab-master/mecab

- name: make php-mecab from source
  shell: make
  args:
    chdir: /tmp/php-mecab-master/mecab

- name: make install php-mecab
  shell: >-
    make install 
    chdir: /tmp/php-mecab-master/mecab

- name: ln php-mecab
  shell: ln -s /usr/lib64/php/modules/mecab.so /etc/php.d
