# main.yml
---
- name: install packages
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - perl-libwww-perl
    - perl-Crypt-SSLeay
    #- perl-LWP-Protocol-https
    - automake
    - gd-devel
    - bc
    - jq
    - python-passlib

- name: create nagios user
  user:
    name: nagios
    shell: /bin/bash

- name: add apache to nagios group
  user:
    name: apache
    groups: nagios
    append: yes

- name: download nagios source
  get_url:  
    url: https://sourceforge.net/projects/nagios/files/nagios-4.x/nagios-4.2.1/nagios-4.2.1.tar.gz
    dest: /usr/local/src

- name: untar nagios source archive
  unarchive:
    src: /usr/local/src/nagios-4.2.1.tar.gz
    dest: /usr/local/src
    copy: no

- name: configure nagios source
  shell: >-
    ./configure --with-command-group=nagios
  args:
    chdir: /usr/local/src/nagios-4.2.1

- name: make nagios from source
  shell: make all
  args:
    chdir: /usr/local/src/nagios-4.2.1

- name: make install nagios
  shell: >-
    make install &&
    make install-commandmode &&
    make install-init &&
    make install-config &&
    make install-webconf
  args:
    chdir: /usr/local/src/nagios-4.2.1

- name: download nagios plugins
  get_url:  
    url: http://nagios-plugins.org/download/nagios-plugins-2.1.3.tar.gz
    dest: /usr/local/src

- name: untar nagios source archive
  unarchive:
    src: /usr/local/src/nagios-plugins-2.1.3.tar.gz
    dest: /usr/local/src
    copy: no

- name: configure nagios plugins
  shell: >-
    ./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl
  args:
    chdir: /usr/local/src/nagios-plugins-2.1.3

- name: make nagios plugins
  shell: make && make install
  args:
    chdir: /usr/local/src/nagios-plugins-2.1.3

- name: create /usr/local/nagios/etc/htpasswd.users
  htpasswd:
    path: /usr/local/nagios/etc/.htpasswd
    name: nagiosadmin
    password: adachinco
    mode: 0644

- name: httpd conf
  copy:
    src: httpd/nagios.conf
    dest: /etc/httpd/conf.d/nagios.conf

#- name: set timezone in /etc/php.ini
#  replace:
#    dest: /etc/php.ini
#    regexp: '^;date.timezone =$'
#    replace: 'date.timezone = Asia/Tokyo'

- name: download the plugin
  get_url:  
    url: https://raw.github.com/tinyspeck/services-examples/master/nagios.pl
    dest: /usr/local/bin/slack_nagios.pl
    mode: 0755

#- name: download check_log3.pl plugin
#  get_url:  
#    url: http://sourceforge.net/projects/pma-oss/files/nagios-plugins/check_log3.pl
#    dest: /usr/lib64/nagios/plugins/
#    mode: 0755

- name: download 3rd party plugins
  get_url:  
    url: "{{ item }}"
    dest: /usr/lib64/nagios/plugins/
    mode: 0755
  with_items:
    - https://raw.githubusercontent.com/cloved/check_traffic/master/check_traffic.sh
    - https://raw.githubusercontent.com/matteocorti/check_ssl_cert/master/check_ssl_cert

- name: edit slack_nagios.pl
  replace:
    dest: /usr/local/bin/slack_nagios.pl
    regexp: 'foo.slack.com'
    replace: 'adachin.slack.com'

- name: edit slack_nagios.pl
  replace:
    dest: /usr/local/bin/slack_nagios.pl
    regexp: '^my\s\$opt_token(.*)$'
    replace: 'my $opt_token = "xxxxxxxxxxx";'

#- name: make nagios from source
#  shell: echo "[$(date +%s)] DISABLE_HOST_SVC_NOTIFICATIONS;{{ host }}" > /usr/local/nagios/var/rw/nagios.cmd

