---
- name: copy nginx conf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.dest }}"
    backup: yes
    owner: root
    group: root
  with_items:
    - { src: roles/nginx/files/nginx.conf, dest: . }
    - { src: roles/nginx/files/sites-enabled/, dest: sites-enabled/ }

- file: path=/var/www/{{ item.name }} state=directory owner=root group=root mode=0755
  with_items:
        - { name: 'adachin' }
        - { name: 'stage' }

