---
- name: nginx yum repository
  copy: 
    src: yum.repos.d/nginx.repo
    dest: /etc/yum.repos.d
    mode: 0644
    owner: root
    group: root

- name: Install nginx
  sudo: True
  yum: name={{ item }} state=present enablerepo=nginx
  with_items:
    - nginx

- name: Delete default configuration
  file: dest=/etc/nginx/conf.d/{{ item }}.conf state=absent
  with_items:
    - default
    - example_ssl

- name: Enable nginx service
  service:
    name: nginx
    enabled: yes
    state: started

