---
- name: install collectd
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - collectd
    #- collectd-curl

- name: collectd.conf
  template:
    src: roles/collectd/templates/collectd.conf.j2
    dest: /etc/collectd.conf
    mode: 0644
    backup: no
  notify: restart collectd

