---
# - debug: msg={{ ansible_distribution }}

- include: install_src.yml
  when:
    - ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat' 
    - ansible_distribution_major_version == '5' or
      ansible_distribution_major_version == '6' 

#- include: roles/collectd/tasks/install_yum.yml
#  when:
#    - ansible_distribution == 'CentOS'
#    - ansible_distribution_major_version == '7'

- include: adachin/lvs.yml
  when: "'lvs' in group_names"

- include: adachin/drc.yml
  when: "'drc' in group_names"

#- include: adachin/deliver.yml
#  when: "'deliver' in group_names"

- name: enable collectd service
  service:
    name: collectd
    state: started
    enabled: yes

