---
- hosts: docker01
  become: yes
  remote_user: docker
  tasks:
    - name: deploy centos container
      docker: image=centos:7 name=web01 privileged=yes  ports=7070:7070 expose=80 tty=yes command=/sbin/init
#      docker: image=centos:6 name=LB-test01 ports=7070:7070 expose=80 tty=yes
 
- hosts: web01
  connection: docker
  tasks:
     - include: roles/common/tasks/yum_update.yml
       tags: update
     - include: roles/common/tasks/yum_repos7.yml
       tags: repos
     - include: roles/common/tasks/main.yml
       tags: main
     - include: roles/common/tasks/user.yml
       tags: user
     - include: roles/nginx/tasks/main.yml
       tags: nginx-install
     - include: roles/nginx/tasks/conf.yml
       tags: nginx-conf
