---
- hosts: aws-ec2
  remote_user: ec2-user
  #become: True
  become: yes
  become_user: root
  pre_tasks:
    - include: roles/common/tasks/hostname.yml
      tags: common
  roles:
    - { role: common, tags: 'common' }
    - { role: nginx, tags: 'nginx' }
    - { role: sshd, tags: 'sshd' }
    - { role: apache, tags: 'apache' }
  tasks:
    - include: roles/common/tasks/user.yml
      tags: common
    - include: roles/nginx/tasks/conf.yml
      tags: nginx-conf
    - include: roles/apache/tasks/conf.yml
      tags: httpd-conf


