- name: LB-conf copy /etc/keepalived
  copy:
    src: "roles/keepalived/files/{{ item.src }}/"
    dest: "/etc/keepalived/{{ item.dest }}"
    backup: yes
    owner: root
    group: root
  with_items:
    - { src: "{{ inventory_hostname }}/", dest: . }

