---
  - name: install package keepalived
     yum: name={{ item }} state=installed
  with_items:
     - ipvsadm
     - keepalived

  - name: copy sysctl.conf
    copy:
     src: "{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
  backup: yes
   owner: root
   group: root
  with_items:
    - { src: roles/keepalived/files/sysctl.conf, dest: . }

  - name: touch ipvsadm in /etc/sysconfig
    file: path=/etc/sysconfig state=file owner=root group=root mode=644

  - name: start ipvsadm service
 service:
    name: ipvsadm
 enabled: yes
   state: started

